### ISSUE TITLE
Inability to reproduce DMPfold result reported in the bioRxiv paper

### ISSUE THREAD

**Issue by kad-ecoli** [Bhattacharya-Lab/DConStruct#1]
Table 3 and Table S5 In the [bioRxiv manuscript for DConStruct](https://doi.org/10.1101/2020.07.05.188466) show that DConStruct outperforms the best state-of-the-art method, DMPfold, on 40 CASP FM target. However, in my own benchmark for a subset of 30 CASP FM targets, in terms of both average and median first model TM-score, DMPfold using DeepMSA significantly outperforms DConStruct, [which presumably also uses DeepMSA according to the manuscript](https://www.biorxiv.org/content/10.1101/2020.07.05.188466v1.full#ref-34). Is there any misunderstanding? Thank you.

|	Target	|	DMPfold+DeepMSA (my run)	|	DMPfold (reported in preprint)	|	DConStruct (reported in preprint)	|
|	:---:	|	:---:	|	:---:	|	:---:	|
|	T0859-D1	|	0.2409	|	0.2446	|	0.1930	|
|	T0862-D1	|	0.8145	|	0.2755	|	0.5056	|
|	T0863-D1	|	0.5063	|	0.2933	|	0.5030	|
|	T0864-D1	|	0.7319	|	0.4792	|	0.6950	|
|	T0866-D1	|	0.7768	|	0.7369	|	0.5820	|
|	T0869-D1	|	0.7054	|	0.7729	|	0.7448	|
|	T0870-D1	|	0.6807	|	0.4912	|	0.6724	|
|	T0886-D1	|	0.3616	|	0.3214	|	0.3042	|
|	T0886-D2	|	0.6716	|	0.6894	|	0.6944	|
|	T0892-D2	|	0.6401	|	0.6411	|	0.6960	|
|	T0897-D2	|	0.6338	|	0.2187	|	0.2031	|
|	T0898-D1	|	0.6875	|	0.3716	|	0.6463	|
|	T0900-D1	|	0.5865	|	0.6207	|	0.6251	|
|	T0912-D3	|	0.6457	|	0.5599	|	0.5784	|
|	T0918-D1	|	0.5534	|	0.5858	|	0.5547	|
|	T0918-D2	|	0.5853	|	0.5632	|	0.3157	|
|	T0918-D3	|	0.5430	|	0.4087	|	0.5148	|
|	T0953s1-D1	|	0.2932	|	0.3567	|	0.3997	|
|	T0953s2-D2	|	0.5296	|	0.5258	|	0.6466	|
|	T0957s1-D1	|	0.4685	|	0.2140	|	0.3496	|
|	T0957s2-D1	|	0.4391	|	0.5481	|	0.7022	|
|	T0968s1-D1	|	0.7228	|	0.6635	|	0.6823	|
|	T0968s2-D1	|	0.8098	|	0.5256	|	0.7371	|
|	T0960-D2	|	0.5688	|	0.2500	|	0.3601	|
|	T0980s1-D1	|	0.3798	|	0.2611	|	0.2905	|
|	T0990-D1	|	0.5153	|	0.5156	|	0.3254	|
|	T0990-D3	|	0.3686	|	0.2625	|	0.2479	|
|	T1021s3-D1	|	0.6117	|	0.3951	|	0.4904	|
|	T1021s3-D2	|	0.2806	|	0.2975	|	0.3345	|
|	T1022s1-D1	|	0.5381	|	0.5253	|	0.2682	|
|	Average	|	0.5630	|	0.4538	|	0.4954	|
|	Median	|	0.5771	|	0.4852	|	0.5102	|

**Comment by rahmatullah-roche** [comment]
We ensured that all competing methods are run with default parameter setting according to their published papers. For DMPfold, we used the target sequences to generate final models as done in the original paper. Not sure of your benchmark, but we have made all input and output data openly available to fully reproduce DConStruct results. And one can always download the competing methods from their published papers to run in their original form with default parameter setting for reproducibility.

**Comment by kad-ecoli** [comment]
Based on what you describe, different MSAs were used for DMPfold and for DConStruct. DMPfold benchmark uses its default MSA (hhblits+uniclust30). DConStruct benchmark uses DeepMSA. This is not clearly explained in the manuscript, which explicitly states that  DMPfold was run with DeepMSA ("We install and run DMPfold locally to predict distance histogram maps directly from the multiple sequence alignments (MSA) [34]").

If that is the case, the performance advantage of DConStruct compared to DMPFold shown in the manuscript is likely caused by better MSA used by DConStruct. This does not indicate that compare to CNS (used by DMPFold), DConStruct has a better ability to fold the protein given the same distance prediction.

**Comment by rahmatullah-roche** [comment]
We never "explicitly" state that "DMPfold was run with DeepMSA" in our manuscript. It is interesting to note your incorrect presumptions and the resulting unfounded conclusions, indicating an apparent bias for DeepMSA [1].

Reference:

[1] Chengxin Zhang, Wei Zheng, S. M. Mortuza, Yang Li, Yang Zhang. “DeepMSA: constructing deep multiple sequence alignment to improve contact prediction and fold-recognition for distant-homology proteins.” Bioinformatics, 36 (7): 2105-2112 (2020).

**Comment by kad-ecoli** [comment]
The sentence I quoted is from section "DConStruct: hybridized distance- and contact-based hierarchical structure modeling" of the DConStruct manuscript.

```
We install and run DMPfold locally to predict distance histogram maps directly from the multiple sequence alignments (MSA) [34]

[34] Zhang C, Zheng W, Mortuza SM, Li Y, Zhang Y. DeepMSA: constructing deep multiple sequence alignment to improve contact prediction and fold-recognition for distant-homology proteins. Bioinformatics. 2020;36: 2105–2112. doi:10.1093/bioinformatics/btz863
```

A similar sentence is from section "Test datasets and programs to compare" of the DConsStruct manuscript.

```
We feed the multiple sequence alignments (MSAs) [34] to DMPfold and obtain the predicted initial distance histograms (rawdispred.current files) containing 20 distance bins with their associated likelihoods
```

In any case, even if my understanding is incorrect, could you explain the following questions:
1. What is the MSA used by "DConsStruct" method in Table 3? Please kindly provide the command line, which is not included in the github repo of DConsStruct.
2. What is the MSA used by "DMPFold" method in Table 3? Again, please kindly provide the command line, as DMPfold can accept arbitrary user input MSA despite having its built-in MSA generation pipeline.
3. Could you provide the link to the MSA files used herein? If the files are too big for all dataset, you can just provide the MSAs for the 40 CASP FM targets.
